version: "3.8"
services:
  db:
    image: mysql/mysql-server:latest
    container_name: myapp-mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: